src/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Is_Valid_For_Rent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>defines if car is available for rent</description>
        <label>Is Valid For Rent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <description>BMW 530, Volvo s50</description>
        <label>Model</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Manager__c.object
<CustomObject>
    <description>Person who works at car rent saloon and helps people to rent proper car.</description>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Sales Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilFactory.cls
/**
 * Created by anast on 19.10.2022.
 */

@IsTest
public class UtilFactory {
    public static List<Sales_Manager__c> createSalesManager(Integer quantity) {
        List<Sales_Manager__c> salesManagers = new List<Sales_Manager__c>();
        for (Integer i = 0; i < quantity; i++) {
            salesManagers.add(new Sales_Manager__c(Name = 'Ana' + i, Email__c = 'ana' + i + '@gmail.com'));
        }
        return salesManagers;
    }

    public static List<Car__c> createCar(Integer quantity) {
        List<Car__c> cars = new List<Car__c>();
        for (Integer i = 0; i < quantity; i++) {
            if (i / 2 == 0) // 0, 2, 4, 6,.. - not valid
                cars.add(new Car__c (Is_Valid_For_Rent__c = false, Model__c = 'Toyota Corova' + i));
            cars.add(new Car__c(Is_Valid_For_Rent__c = true, Model__c = 'Lada Baklazhan' + i));
        }
        return cars;
    }
}