src/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <description>BMW 530, Volvo s50</description>
        <label>Model</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time periods) and same car may have many deals made by various Sales Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Car__c.Type__c</field>
                <operation>equals</operation>
                <value>Sedan, Minivan, Hatchback</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of rent</description>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <referenceTo>Sales_Manager__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>DATETIMEVALUE(TODAY())</defaultValue>
        <description>Start date of rent, Default Today</description>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Open (DEFAULT) - there is a cliend who called and asked for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <inlineHelpText>(Open, Won, Lost) Status of rent.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Manager__c.object
<CustomObject>
    <description>Person who works at car rent saloon and helps people to rent proper car.</description>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LastRaiseDate__c</fullName>
        <label>LastRaiseDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalaryRaiseBatchTest.cls
/**
 * Created by anast on 27.10.2022.
 */

@IsTest
private class SalaryRaiseBatchTest {
    @TestSetup
    static void setup() {
        List<Sales_Manager__c> smList = new List<Sales_Manager__c>();
        for (Integer i = 0; i < 200; i++) {
            smList.add(new Sales_Manager__c(Name = 'Alice' + i, Email__c = 'alice' + i + '@gmail.com',
                    LastRaiseDate__c = Date.newInstance(2020, 07, 01),
                    Salary__c = 100));
        }
        insert smList;

        List<Car__c> cars = new List<Car__c>();
        for (Integer i = 0; i < 200; i++) {
            cars.add(new Car__c(Name = 'car' + i, Model__c = 'sedan' + i));
        }
        insert cars;

        List<Deal__c> paramDeals = new List<Deal__c>();
        for (Integer i = 0; i < 200; i++) {
            paramDeals.add(new Deal__c(Status__c = 'Open', Sales_Manager__c = smList.get(i).Id,
                    Start_Date__c = Datetime.newInstance(2021, 07, 01),
                    End_Date__c = Datetime.newInstance(2022, 09, 01),
                    Car__c = cars.get(i).Id));
        }
        insert paramDeals;

        for (Deal__c d : paramDeals)
            d.Status__c = 'Won'; //today?
        update paramDeals;
    }

    @IsTest
    static void testSalaryBatch() {
        Test.startTest();
        SalaryRaiseBatch job = new SalaryRaiseBatch();
        Id batchId = Database.executeBatch(job);
        Test.stopTest();

        List<Sales_Manager__c> managersToCheck = [SELECT Id, Salary__c, LastRaiseDate__c FROM Sales_Manager__c];

        System.assert(!managersToCheck.isEmpty(),'Empty list!'); //check for emptiness of the list
        for (Sales_Manager__c sales : managersToCheck) {
            System.assertEquals(110, sales.Salary__c, 'Wrong salary!');
            System.assertEquals(System.today(), sales.LastRaiseDate__c, 'Last raise is today!');
        }
    }
}