src/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time periods) and same car may have many deals made by various Sales Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Car__c.Type__c</field>
                <operation>equals</operation>
                <value>Sedan, Minivan, Hatchback</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of rent</description>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>DATETIMEVALUE(TODAY())</defaultValue>
        <description>Start date of rent, Default Today</description>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Open (DEFAULT) - there is a cliend who called and asked for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <inlineHelpText>(Open, Won, Lost) Status of rent.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DealTriggerHandler.cls
/**
 * Created by anast on 17.10.2022.
 */

public with sharing class DealTriggerHandler {
    public static void onBeforeInsert(List<Deal__c> deals) { // list of new deals we are creating
        List<Deal__c> wonLostDeals = [
                SELECT Id, Name, Start_Date__c, End_Date__c, Status__c, Car__c
                FROM Deal__c
                WHERE Status__c = 'Won' OR Status__c = 'Open'
        ];
        //IMPORTANT! we ALWAYS create OPEN deals
        for (Deal__c paramDeal : deals) {
            for (Deal__c deal : wonLostDeals) {
                if (paramDeal.Car__c == deal.Car__c
                        && paramDeal.Start_Date__c == deal.Start_Date__c
                        && paramDeal.End_Date__c == deal.End_Date__c && paramDeal.Status__c!='Lost')
                    paramDeal.addError('You\'re trying to create a duplicate');
            }
        }
    }
}



//        Set<Deal__c> dealSet = new Set<Deal__c>();
//        for (Deal__c d : deals) {
//            dealSet.add(d);
//            if (dealSet.size() != deals.size())
//                d.addError('Duplicate!');
//        }

//        List<Deal__c> cloneDeals = deals.deepClone(); // to find the duplicates among deals before the insert
//        for (Deal__c paramDeal : deals) {
//            for (Deal__c clone : cloneDeals) {
//                if (paramDeal.Car__c == clone.Car__c
//                        && paramDeal.Start_Date__c == clone.Start_Date__c
//                        && paramDeal.End_Date__c == clone.End_Date__c)
//                    paramDeal.addError('You\'re trying to create a duplicate');
//            }
//        }