src/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Is_Valid_For_Rent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>defines if car is available for rent</description>
        <label>Is Valid For Rent</label>
        <type>Checkbox</type>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time periods) and same car may have many deals made by various Sales Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Car__c.Type__c</field>
                <operation>equals</operation>
                <value>Sedan, Minivan, Hatchback</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Open (DEFAULT) - there is a cliend who called and asked for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <inlineHelpText>(Open, Won, Lost) Status of rent.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CarTriggerHandler.cls
/**
 * Created by anast on 17.10.2022.
 */

public with sharing class CarTriggerHandler {
    public static void onAfterInsert(List<Car__c> cars) {
        List<Car__c> notValidCars = new List<Car__c>();
        for (Car__c car : cars) {
            if (!car.Is_Valid_For_Rent__c)
                notValidCars.add(car);
        }
        if (notValidCars.size() > 0) {
            List<Deal__c> deals = [SELECT Id FROM Deal__c WHERE Status__c = 'Open' AND Car__r.Id IN :notValidCars];
            for (Deal__c deal : deals) {
                deal.Status__c = 'Lost';
            }
            update deals;
        }
    }
}