src/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time periods) and same car may have many deals made by various Sales Managers.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.Is_Valid_For_Rent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Car__c.Type__c</field>
                <operation>equals</operation>
                <value>Sedan, Minivan, Hatchback</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of rent</description>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <referenceTo>Sales_Manager__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>DATETIMEVALUE(TODAY())</defaultValue>
        <description>Start date of rent, Default Today</description>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Manager__c.object
<CustomObject>
    <description>Person who works at car rent saloon and helps people to rent proper car.</description>
    <label>Sales Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DealTriggerTest.cls
/**
 * Created by anast on 20.10.2022.
 */

@IsTest
private class DealTriggerTest {
 //   static List<Deal__c> deals = new List<Deal__c>();
    static List<Sales_Manager__c> sales = UtilFactory.createSalesManager(10);
    static List<Car__c> cars = UtilFactory.createCar(10); // 5 valid + 5 not valid

    @IsTest
    static void duplicatedDealTest() {
        insert sales;
        insert cars;
        Deal__c deals1 = new Deal__c(Start_Date__c = DateTime.newInstance(2000, 1, 28),
                End_Date__c = DateTime.newInstance(2002, 1, 28),
                Sales_Manager__c = sales.get(2).Id,
                Car__c = cars.get(1).Id);

        Deal__c deals2 = new Deal__c(Start_Date__c = Datetime.newInstance(2021, 1, 29),
                End_Date__c = DateTime.newInstance(2021, 5, 28),
                Sales_Manager__c = sales.get(2).Id,
                Car__c = cars.get(3).Id);

        Deal__c deals3 = new Deal__c(Start_Date__c = Datetime.newInstance(2021, 1, 29),
                End_Date__c = DateTime.newInstance(2021, 5, 28),
                Sales_Manager__c = sales.get(2).Id,
                Car__c = cars.get(3).Id);

        Test.startTest();
        Database.SaveResult result1 = Database.insert(deals1, false);
        Database.SaveResult result2 = Database.insert(deals2, false);
        Database.SaveResult result3 = Database.insert(deals3, false);
        Test.stopTest();

        System.assert(result1.isSuccess(), 'DealTriggerHandler.onBeforeInsert: not duplicate');
        System.assert(result2.isSuccess(), 'DealTriggerHandler.onBeforeInsert: not duplicate');
        System.assert(!result3.isSuccess(), 'DealTriggerHandler.onBeforeInsert: this is a duplicate');
        System.assertEquals(result3.getErrors()[0].getMessage(), 'You\'re trying to create a duplicate',
                'DealTriggerHandler.onBeforeInsert: there must be an error!');

    }
}