src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time periods) and same car may have many deals made by various Sales Managers.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of rent</description>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Open (DEFAULT) - there is a cliend who called and asked for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <inlineHelpText>(Open, Won, Lost) Status of rent.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CarRentServices.cls
/**
 * Created by anast on 09.10.2022.
 */

public with sharing class CarRentServices {

    // will receive list of records and set End_Date__c to today
    public void setEndDate(List<Deal__c> list) {
        for (Deal__c deal : list) {
            deal.End_Date__c = System.today();
        }
    }


// return Rent deals that are Won or Lost. Input params: List<Deal__c> deals, String status.
// The method should return List<Deal__c> filtered by Status__c.

    public List<Deal__c> fillterFinished(List<Deal__c> deals, String status) {
        List<Deal__c> result = new List<Deal__c>();
        for (Deal__c deal : deals) {
            if (deal.Status__c == status)
                result.add(deal);
        }
        return result;
    }
}