src/objects/Deal__c.object
<CustomObject>
    <description>Sales Manager may have many deals for same car (different time periods) and same car may have many deals made by various Sales Managers.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of rent</description>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <referenceTo>Sales_Manager__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Open (DEFAULT) - there is a cliend who called and asked for a car. Car was reserved but no money paid yet.
Won - deal was successfull, money paid, car rent.
Lost - client refused to pay or cancelled the order.</description>
        <inlineHelpText>(Open, Won, Lost) Status of rent.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Manager__c.object
<CustomObject>
    <description>Person who works at car rent saloon and helps people to rent proper car.</description>
    <fields>
        <fullName>LastRaiseDate__c</fullName>
        <label>LastRaiseDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalaryRaiseBatch.cls
/**
 * Created by anast on 27.10.2022.
 */

public class SalaryRaiseBatch implements Database.Batchable<SObject>, Schedulable {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
                'SELECT Id, Salary__c, LastRaiseDate__c FROM Sales_Manager__c WHERE LastRaiseDate__c <= LAST_N_MONTHS:6');
    }
    public void execute(Database.BatchableContext bc, List<Sales_Manager__c> sales) {
        for (Deal__c deal : [
                SELECT Id, Sales_Manager__r.Id
                FROM Deal__c
                WHERE End_Date__c >= LAST_N_MONTHS:6 AND Status__c = 'Won'
        ]) {
            for (Sales_Manager__c sm : sales) {
                if (deal.Sales_Manager__r.Id == sm.Id) {
                    sm.Salary__c += 10;
                    sm.LastRaiseDate__c = System.today();
                }
            }
        }
        update sales;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Sales managers records processed. Congrats!');
    }

    public void execute(SchedulableContext context) {
        SalaryRaiseBatch raiseBatch = new SalaryRaiseBatch();
        Id batchId = Database.executeBatch(raiseBatch);
    }
}